"""Prefix-aware SQL DDL emission for an ``L2Instance`` (M.1.4 + M.1.5).

Emits one idempotent (drop-then-create) DDL script per L2 instance,
prefixed per the SPEC's storage-isolation rule (F10):

  ``<prefix>transactions``           — base table; L1 ``Transaction``
                                       denormalized with Account +
                                       Transfer fields per the
                                       Implementation Entities section.
  ``<prefix>daily_balances``         — base table; L1 ``StoredBalance``
                                       denormalized with Account fields.
  ``<prefix>current_transactions``   — view; the L1 ``CurrentTransaction``
                                       theorem materialized as max-Entry-
                                       per-ID over the base table.
  ``<prefix>current_daily_balances`` — view; the L1 ``CurrentStoredBalance``
                                       theorem materialized as max-Entry-
                                       per-(account, business_day) over
                                       the base table.

Plus B-tree indexes for the dashboard's hot-path queries on the bases.

The dashboard SQL targets the ``current_*`` views, never the bases —
that way Entry-supersession (technical-error correction per the F1
principle) is transparent to dashboard consumers.

What is NOT emitted as SQL tables (per the M.0 spike's experience):
- L2's account topology (Roles, AccountTemplates, parent_role chains) —
  the relevant fields denormalize onto the transactions / daily_balances
  rows; no separate dim table needed for v1.
- L2's Limits — projected into the ``daily_balances.limits`` Map column
  by integrator ETL; no separate limits table.
- L2's Chains, TransferTemplates — read by dashboard SQL at view-build
  time (the SQL string knows which TransferTypes can chain into which
  via L2 lookups), not materialized as tables.

The "minimum SQL surface" stance follows from the spike: M.2 (porting
AR CMS) will surface what L2 derived tables are actually needed beyond
the base layer. Add them then.
"""

from __future__ import annotations

from .primitives import L2Instance


def emit_schema(instance: L2Instance) -> str:
    """Emit the full DDL script for an L2 instance's prefixed L1 base tables.

    Idempotent: every CREATE is preceded by a DROP IF EXISTS so re-running
    the same `apply schema` clears stale state. The returned string can
    be fed straight to ``psql`` or ``psycopg2.cursor.execute(sql)``.

    Per L1 SPEC: the v6 schema differs from v5 in three load-bearing
    ways — adds ``entry BIGSERIAL`` for append-only supersession (F's
    Entry primitive), splits the v5 ``signed_amount`` into the v6
    ``amount_money + amount_direction`` per the L1 Amount invariant
    (money agrees with direction), and adds ``transfer_parent_id``
    for the L1 Transfer.Parent recursive chain (PR pipeline support).
    """
    p = instance.instance
    return _SCHEMA_TEMPLATE.format(p=p)


_SCHEMA_TEMPLATE = """\
-- =====================================================================
-- L2 instance: {p}
-- Generated by quicksight_gen.common.l2.schema.emit_schema
-- =====================================================================

-- Drop views first (they depend on the base tables).
DROP VIEW IF EXISTS {p}_current_daily_balances;
DROP VIEW IF EXISTS {p}_current_transactions;
DROP INDEX IF EXISTS idx_{p}_transactions_account_posting;
DROP INDEX IF EXISTS idx_{p}_transactions_transfer;
DROP INDEX IF EXISTS idx_{p}_transactions_type_status;
DROP INDEX IF EXISTS idx_{p}_transactions_business_day;
DROP INDEX IF EXISTS idx_{p}_transactions_parent;
DROP INDEX IF EXISTS idx_{p}_daily_balances_business_day;
DROP TABLE IF EXISTS {p}_daily_balances CASCADE;
DROP TABLE IF EXISTS {p}_transactions  CASCADE;

-- ---------------------------------------------------------------------
-- L1 Transaction (denormalized with Transfer + Account fields per
-- Implementation Entities: StoredTransaction = Transaction + Transfer,
-- with Account fields also denormalized onto each leg).
--
-- entry         — BIGSERIAL append-only supersession key per L1 F's
--                 Entry primitive. Higher entry overrides lower for the
--                 same logical Transaction.id (Current* view in M.1.5).
-- amount_money  — signed Decimal per L1 Amount's "money agrees with
--                 direction" invariant. Positive ⇔ Credit; negative
--                 ⇔ Debit. The CHECK enforces sign-direction agreement.
-- transfer_parent_id — L1 Transfer.Parent recursive chain (the PR
--                 pipeline support added in Phase L's L1 spec work).
-- origin        — open enum, no CHECK; integrators may extend.
-- metadata      — TEXT + IS JSON (portability constraint: no JSONB,
--                 no GIN indexes; SQL/JSON path syntax for extraction).
-- ---------------------------------------------------------------------
CREATE TABLE {p}_transactions (
    entry                BIGSERIAL      NOT NULL,
    id                   VARCHAR(100)   NOT NULL,
    account_id           VARCHAR(100)   NOT NULL,
    account_name         VARCHAR(255),
    account_role         VARCHAR(100),
    account_scope        VARCHAR(20)    NOT NULL
        CHECK (account_scope IN ('internal', 'external')),
    account_parent_role  VARCHAR(100),
    amount_money         DECIMAL(20,2)  NOT NULL,
    amount_direction     VARCHAR(20)    NOT NULL
        CHECK (amount_direction IN ('Debit', 'Credit')),
    status               VARCHAR(50)    NOT NULL,
    posting              TIMESTAMPTZ    NOT NULL,
    transfer_id          VARCHAR(100)   NOT NULL,
    transfer_type        VARCHAR(50)    NOT NULL,
    transfer_completion  TIMESTAMPTZ,
    transfer_parent_id   VARCHAR(100),
    origin               VARCHAR(50)    NOT NULL,
    metadata             TEXT,
    PRIMARY KEY (id, entry),
    -- Sign-direction agreement (L1 Amount INVARIANT):
    --   money ≥ 0 if direction = Credit; money ≤ 0 if direction = Debit.
    CHECK (
        (amount_direction = 'Credit' AND amount_money >= 0)
        OR
        (amount_direction = 'Debit'  AND amount_money <= 0)
    ),
    CHECK (metadata IS NULL OR metadata IS JSON)
);

-- ---------------------------------------------------------------------
-- L1 StoredBalance (denormalized with Account fields per Implementation
-- Entities: DailyBalance = StoredBalance + Account).
--
-- entry         — same supersession semantic as transactions.entry.
--                 Highest entry per (account_id, business_day_start)
--                 wins; older entries stay for audit.
-- expected_eod_balance — L1 ExpectedEODBalance. NULL means "no
--                 expectation" (the constraint doesn't apply).
-- limits        — JSON map of TransferType → cap, projected from L2's
--                 LimitSchedule entries by the integrator's ETL. NULL
--                 means no limit enforcement on this account-day.
-- money         — signed; CAN go negative (overdraft is observable per
--                 L1's Non-negative Stored Balance SHOULD constraint).
-- ---------------------------------------------------------------------
CREATE TABLE {p}_daily_balances (
    entry                  BIGSERIAL      NOT NULL,
    account_id             VARCHAR(100)   NOT NULL,
    account_name           VARCHAR(255),
    account_role           VARCHAR(100),
    account_scope          VARCHAR(20)    NOT NULL
        CHECK (account_scope IN ('internal', 'external')),
    account_parent_role    VARCHAR(100),
    expected_eod_balance   DECIMAL(20,2),
    business_day_start     TIMESTAMPTZ    NOT NULL,
    business_day_end       TIMESTAMPTZ    NOT NULL,
    money                  DECIMAL(20,2)  NOT NULL,
    limits                 TEXT,
    PRIMARY KEY (account_id, business_day_start, entry),
    CHECK (business_day_end > business_day_start),
    CHECK (limits IS NULL OR limits IS JSON)
);

-- B-tree indexes for the dashboard's hot-path queries. No GIN on
-- TEXT/JSON columns per the SPEC's portability constraint.
CREATE INDEX idx_{p}_transactions_account_posting ON {p}_transactions (account_id, posting);
CREATE INDEX idx_{p}_transactions_transfer        ON {p}_transactions (transfer_id);
CREATE INDEX idx_{p}_transactions_type_status     ON {p}_transactions (transfer_type, status);
CREATE INDEX idx_{p}_transactions_parent          ON {p}_transactions (transfer_parent_id);
CREATE INDEX idx_{p}_daily_balances_business_day  ON {p}_daily_balances (business_day_start);

-- ---------------------------------------------------------------------
-- Current* views (M.1.5) — materialize the L1 ``CurrentTransaction`` /
-- ``CurrentStoredBalance`` theorems as max-Entry-per-logical-key over
-- the base tables. Per the SPEC's set-comprehension definitions:
--
--   CurrentTransaction := {{ tx ∈ Transaction :
--     tx.Entry = max(Transaction(ID = tx.ID).Entry) }}
--   CurrentStoredBalance := {{ sb ∈ StoredBalance :
--     sb.Entry = max(StoredBalance(Account = sb.Account,
--                                  BusinessDay = sb.BusinessDay).Entry) }}
--
-- The dashboard SQL targets these views, NOT the base tables — that way
-- Entry-supersession (technical-error correction per L1's Immutability
-- principle) is transparent to dashboard consumers. A wrong row stays
-- visible in the base table for audit; the view returns the corrected one.
-- ---------------------------------------------------------------------
CREATE VIEW {p}_current_transactions AS
SELECT * FROM {p}_transactions tx
WHERE tx.entry = (
    SELECT MAX(entry) FROM {p}_transactions WHERE id = tx.id
);

CREATE VIEW {p}_current_daily_balances AS
SELECT * FROM {p}_daily_balances sb
WHERE sb.entry = (
    SELECT MAX(entry)
    FROM {p}_daily_balances
    WHERE account_id = sb.account_id
      AND business_day_start = sb.business_day_start
);
"""
