"""M.0 spike — emitters for schema SQL, seed SQL, dashboard JSON, handbook page.

Each emit_* / build_* / render_* function takes the loaded `L2Instance` and
emits one piece of the deployed surface. They land in this single module
during the spike for compactness; M.1 splits them into proper layered
modules under `common/l2/`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from quicksight_gen.common.config import Config
from quicksight_gen.common.dataset_contract import (
    ColumnSpec,
    DatasetContract,
    build_dataset,
)
from quicksight_gen.common.ids import SheetId
from quicksight_gen.common.tree import Analysis, App, Dataset, Sheet

from .loader import L2Instance


# -- Schema SQL ---------------------------------------------------------------


def emit_schema_sql(inst: L2Instance) -> str:
    """Emit DDL for the prefixed L1 base tables + Current* views.

    Returns one SQL script (semicolon-separated) intended for `apply schema`
    to feed straight into `psql`. The script is idempotent — drops then
    recreates everything under the instance's prefix. Per the SPEC's
    Implementation Entities, Account fields denormalize onto every
    transaction/balance row; Transfer fields denormalize onto every
    transaction row. No separate dimension tables.
    """
    p = inst.instance
    return f"""\
-- =====================================================================
-- L2 instance: {p}
-- Generated by quicksight_gen.l2_spike.emit.emit_schema_sql
-- =====================================================================

DROP VIEW IF EXISTS {p}_current_daily_balances;
DROP VIEW IF EXISTS {p}_current_transactions;
DROP TABLE IF EXISTS {p}_daily_balances;
DROP TABLE IF EXISTS {p}_transactions;

-- L1 Transaction (denormalized with Transfer + Account fields per
-- Implementation Entities: StoredTransaction = Transaction + Transfer,
-- with Account fields also denormalized onto each leg).
CREATE TABLE {p}_transactions (
    id              TEXT NOT NULL,
    entry           BIGSERIAL NOT NULL,
    account_id      TEXT NOT NULL,
    account_name    TEXT,
    account_scope   TEXT NOT NULL CHECK (account_scope IN ('internal', 'external')),
    amount_money    NUMERIC(20, 2) NOT NULL,
    amount_direction TEXT NOT NULL CHECK (amount_direction IN ('Debit', 'Credit')),
    status          TEXT NOT NULL,
    posting         TIMESTAMPTZ NOT NULL,
    transfer_id     TEXT NOT NULL,
    transfer_type   TEXT NOT NULL,
    transfer_completion TIMESTAMPTZ,
    origin          TEXT NOT NULL,
    metadata        TEXT,
    PRIMARY KEY (id, entry)
);

-- L1 StoredBalance (denormalized with Account fields per Implementation
-- Entities: DailyBalance = StoredBalance + Account).
CREATE TABLE {p}_daily_balances (
    entry              BIGSERIAL NOT NULL,
    account_id         TEXT NOT NULL,
    account_name       TEXT,
    account_scope      TEXT NOT NULL CHECK (account_scope IN ('internal', 'external')),
    business_day_start TIMESTAMPTZ NOT NULL,
    business_day_end   TIMESTAMPTZ NOT NULL,
    money              NUMERIC(20, 2) NOT NULL,
    PRIMARY KEY (account_id, business_day_start, entry)
);

-- L1 CurrentTransaction theorem: highest-Entry row per logical Transaction ID.
-- Spike has no Entry-supersession in the seed, so this degenerates to the
-- base table — but the view exists so the dashboard SQL targets the same
-- shape it will in M.1+ when supersession is exercised.
CREATE VIEW {p}_current_transactions AS
SELECT * FROM {p}_transactions tx
WHERE tx.entry = (
    SELECT MAX(entry) FROM {p}_transactions WHERE id = tx.id
);

-- L1 CurrentStoredBalance theorem: highest-Entry row per (account, business_day).
CREATE VIEW {p}_current_daily_balances AS
SELECT * FROM {p}_daily_balances sb
WHERE sb.entry = (
    SELECT MAX(entry)
    FROM {p}_daily_balances
    WHERE account_id = sb.account_id
      AND business_day_start = sb.business_day_start
);
"""


# -- Seed SQL -----------------------------------------------------------------


def emit_seed_sql(inst: L2Instance) -> str:
    """Emit deterministic seed data planting the drift scenario.

    Five $100 ach inbound transfers from `ext-001` → `int-001`, posted across
    a single business day (2026-04-25). One StoredBalance for `int-001` on
    that day reads $450 — $50 short of the $500 sum of posted transactions.
    Drift exception fires for (int-001, 2026-04-25).

    External accounts get no StoredBalance per L1 BusinessDay-enclosure
    constraint (only Internal scope MUST have enclosures).

    The spike's seed is hand-coded against the specific shape of the spike
    instance. M.1+ replaces this with a generator that drives off the loaded
    L2 instance.
    """
    p = inst.instance

    # Pull display-name + scope by id from the loaded instance so the seed
    # rows carry the same denormalized metadata the schema declares.
    by_id = {a.id: a for a in inst.accounts}
    int_acc = by_id["int-001"]
    ext_acc = by_id["ext-001"]

    # 5 transfers, posted at 09:00, 11:00, 13:00, 15:00, 17:00 UTC on
    # 2026-04-25. Each transfer = 1 ext-001 debit + 1 int-001 credit, $100.
    times = [
        "2026-04-25T09:00:00+00:00",
        "2026-04-25T11:00:00+00:00",
        "2026-04-25T13:00:00+00:00",
        "2026-04-25T15:00:00+00:00",
        "2026-04-25T17:00:00+00:00",
    ]

    transaction_rows: list[str] = []
    for i, ts in enumerate(times, start=1):
        transfer_id = f"t-{i:03d}"

        # Debit leg on ext-001 (signed -100).
        transaction_rows.append(_txn_row(
            id_=f"tx-{i:03d}-debit",
            account_id=ext_acc.id,
            account_name=ext_acc.name or "",
            account_scope=ext_acc.scope,
            money="-100.00",
            direction="Debit",
            posting=ts,
            transfer_id=transfer_id,
            metadata=f'{{"external_reference": "ER-{i:03d}"}}',
        ))

        # Credit leg on int-001 (signed +100).
        transaction_rows.append(_txn_row(
            id_=f"tx-{i:03d}-credit",
            account_id=int_acc.id,
            account_name=int_acc.name or "",
            account_scope=int_acc.scope,
            money="100.00",
            direction="Credit",
            posting=ts,
            transfer_id=transfer_id,
            metadata=f'{{"external_reference": "ER-{i:03d}"}}',
        ))

    transactions_insert = "INSERT INTO {p}_transactions (id, account_id, account_name, account_scope, amount_money, amount_direction, status, posting, transfer_id, transfer_type, transfer_completion, origin, metadata) VALUES\n  ".format(p=p) + ",\n  ".join(transaction_rows) + ";"

    # One StoredBalance for int-001 on 2026-04-25; money=$450, drift=$50 low.
    daily_balance_insert = (
        f"INSERT INTO {p}_daily_balances "
        "(account_id, account_name, account_scope, business_day_start, business_day_end, money) VALUES\n"
        f"  ('{int_acc.id}', '{int_acc.name}', '{int_acc.scope}', "
        "'2026-04-25T00:00:00+00:00', '2026-04-26T00:00:00+00:00', 450.00);"
    )

    return f"""\
-- =====================================================================
-- L2 instance: {p} — seed data
-- Generated by quicksight_gen.l2_spike.emit.emit_seed_sql
-- Plants the drift scenario: 5 ach inbound transfers totalling $500 on
-- int-001, but the day's StoredBalance reads $450 (drift = -$50).
-- =====================================================================

{transactions_insert}

{daily_balance_insert}
"""


def _txn_row(
    *,
    id_: str,
    account_id: str,
    account_name: str,
    account_scope: str,
    money: str,
    direction: str,
    posting: str,
    transfer_id: str,
    metadata: str,
) -> str:
    """Build a single VALUES row for a transactions INSERT."""
    return (
        f"('{id_}', '{account_id}', '{account_name}', '{account_scope}', "
        f"{money}, '{direction}', 'Posted', '{posting}', "
        f"'{transfer_id}', 'ach', NULL, 'ExternalForcePosted', '{metadata}')"
    )


# -- Dashboard ----------------------------------------------------------------


_DRIFT_CONTRACT = DatasetContract(
    columns=[
        ColumnSpec(name="account_id", type="STRING"),
        ColumnSpec(name="account_name", type="STRING"),
        ColumnSpec(name="business_day_end", type="DATETIME"),
        ColumnSpec(name="stored_money", type="DECIMAL"),
        ColumnSpec(name="computed_money", type="DECIMAL"),
        ColumnSpec(name="drift", type="DECIMAL"),
    ],
)


def _drift_sql(prefix: str) -> str:
    """The CUSTOM_SQL behind the Drift dataset.

    Per L1: Drift(account, day) = StoredBalance.Money − ComputedBalance.
    Surfaces only rows where Drift ≠ 0 (the SHOULD violation).
    """
    return f"""\
SELECT
    sb.account_id,
    sb.account_name,
    sb.business_day_end,
    sb.money AS stored_money,
    COALESCE(t.computed_money, 0)            AS computed_money,
    sb.money - COALESCE(t.computed_money, 0) AS drift
FROM {prefix}_current_daily_balances sb
LEFT JOIN (
    SELECT
        account_id,
        SUM(amount_money) AS computed_money
    FROM {prefix}_current_transactions
    WHERE status = 'Posted'
    GROUP BY account_id
) t ON t.account_id = sb.account_id
WHERE sb.account_scope = 'internal'
  AND sb.money - COALESCE(t.computed_money, 0) <> 0"""


def build_dashboard(inst: L2Instance, cfg: Config) -> App:
    """Build the Drift dashboard App for the spike instance.

    1 sheet ("Drift") with 1 KPI (drift exception count) + 1 detail table.
    The CUSTOM_SQL Dataset query computes Drift per-account and filters
    to non-zero rows only.
    """
    # Build the API-side DataSet (registers the contract under "drift-view")
    # then wrap in the tree Dataset node so visuals can subscript-resolve
    # ds["col"] against the registered contract.
    api_dataset = build_dataset(
        cfg,
        cfg.prefixed("drift-dataset"),
        "Drift Detail",
        "drift-view",
        _drift_sql(inst.instance),
        _DRIFT_CONTRACT,
        visual_identifier="drift-view",
    )
    drift_ds = Dataset(
        identifier="drift-view",
        arn=cfg.dataset_arn(api_dataset.DataSetId),
    )

    app = App(name="spike-drift", cfg=cfg)
    analysis = app.set_analysis(Analysis(
        analysis_id_suffix="spike-drift-analysis",
        name="Drift Exceptions",
    ))
    app.add_dataset(drift_ds)

    sheet = analysis.add_sheet(Sheet(
        sheet_id=SheetId("drift-sheet"),
        name="Drift",
        title="Drift Exceptions",
        description=(
            "Sub-ledger drift surfaces when stored daily balance "
            "≠ Σ posted transactions for an internal account."
        ),
    ))

    sheet.layout.row(height=8).add_kpi(
        width=36,
        title="Drift Exceptions",
        subtitle="Count of (account, day) tuples where stored ≠ computed",
        values=[drift_ds["account_id"].count()],
    )

    sheet.layout.row(height=12).add_table(
        width=36,
        title="Drift Detail",
        subtitle=(
            "Per (account, business day) row showing stored vs computed "
            "balance and the drift amount"
        ),
        columns=[
            drift_ds["account_name"].dim(),
            drift_ds["business_day_end"].date(),
            drift_ds["stored_money"].numerical(),
            drift_ds["computed_money"].numerical(),
            drift_ds["drift"].numerical(),
        ],
    )

    app.create_dashboard(
        dashboard_id_suffix="spike-drift-dashboard",
        name="Drift Exceptions",
    )
    return app


# -- Handbook -----------------------------------------------------------------


_HANDBOOK_TEMPLATE = """\
# What's a drift exception?

A **drift exception** fires when an internal account's stored daily balance
doesn't match the sum of posted transactions for that account on that day.
The stored balance comes from upstream as a snapshot; the transaction sum
is computed from the ledger. When they disagree, something between the
upstream feed and the ledger has lost (or invented) money.

In this institution, account **{int_account_name}** (`{int_account_id}`)
is currently showing a drift on its most recent business day. The
screenshot below shows the Drift sheet on the deployed dashboard:

![Drift sheet]({screenshot_path})

## What to do

1. **Check the upstream feed** for `{int_account_name}` — confirm whether
   any transactions for the affected day were dropped, double-counted, or
   posted to the wrong account.
2. **Compare stored vs computed** in the table above to see the magnitude
   and direction of the gap. Stored < computed means the snapshot missed
   a posted transaction; stored > computed means the snapshot reflects
   money the ledger doesn't see.
3. **Re-run the daily ETL** once the upstream is fixed. The next
   StoredBalance entry will supersede the one driving the alert, and the
   exception will clear automatically.
"""


def render_handbook(inst: L2Instance, screenshot_path: str = "drift-sheet.png") -> str:
    """Render the spike's one handbook page against the L2 instance vocabulary.

    Substitutes the internal account's display name + ID into the template
    so an integrator's dashboard handbook describes their actual accounts —
    not Sasquatch ones. ``screenshot_path`` is the path that gets embedded
    in the rendered markdown — the caller wires this from
    ``capture_drift_screenshot()`` (M.0.8) once a real PNG has been
    captured against the deployed dashboard.
    """
    int_acc = next(a for a in inst.accounts if a.id == "int-001")
    return _HANDBOOK_TEMPLATE.format(
        int_account_name=int_acc.name or int_acc.id,
        int_account_id=int_acc.id,
        screenshot_path=screenshot_path,
    )


# -- Screenshot capture (M.0.8) -----------------------------------------------


def capture_drift_screenshot(
    app: App,
    output_dir: Path,
    *,
    page: Any,
    embed_url: str,
) -> Path:
    """Run ScreenshotHarness against the deployed dashboard, return the Drift sheet PNG path.

    Requires a live Playwright Page + a fresh embed URL from the deployed
    QuickSight dashboard. Invoked by the CLI's ``generate training`` after
    ``apply dashboards`` has actually deployed (the spike's CLI sets up
    Playwright + fetches the embed URL; ScreenshotHarness handles the rest).
    """
    from quicksight_gen.common.browser import ScreenshotHarness

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    harness = ScreenshotHarness(
        app=app,
        page=page,
        output_dir=output_dir,
        embed_url=embed_url,
    )
    paths = harness.capture_all_sheets()

    # Spike has only one sheet; pull its Path back out by Sheet object ref.
    if app.analysis is None or not app.analysis.sheets:
        raise RuntimeError(f"App {app.name!r} has no sheets to capture.")
    drift_sheet = app.analysis.sheets[0]
    if drift_sheet not in paths:
        raise RuntimeError(
            f"ScreenshotHarness did not produce a screenshot for "
            f"sheet {drift_sheet.name!r}. Captured: "
            f"{[s.name for s in paths]!r}"
        )
    return paths[drift_sheet]
